language: java
jdk: oraclejdk8
script: "./gradlew clean build publishToRepo"
after_success:
- "./gradlew jacocoTestReport coveralls"
env:
  global:
    secure: IZUFECrJgpt23u/rbSx8Lv2Yg+NfQa58vrHAU51Gym3NGA4E+W5rf2Eqvmfpgxd/dFkRwbAl0u26fVOOmSOjWN3go16TY5jea5Fimz4y2ROvNekhYMFAbUiZBKsbcLUeuHh1TvdM9rSR+Rsk6Y8tYwMnczlB3XXVrwi7hAjmrfY=
